FROM tari-labs/rust:nightly as builder

WORKDIR /opt/tarpaulin

RUN env USER=root cargo init .

COPY Cargo.toml .
COPY Cargo.lock .
COPY build.rs .

RUN mkdir .cargo
RUN cargo vendor > .cargo/config

COPY src /opt/tarpaulin/src

RUN cd /opt/tarpaulin/ && \
    cargo install --locked --path . && \
    rm -rf /opt/tarpaulin/ && \
    rm -rf /usr/local/cargo/registry/

FROM tari-labs/rust:nightly

COPY --from=builder /usr/local/cargo/bin/cargo-tarpaulin /usr/local/cargo/bin/cargo-tarpaulin

WORKDIR /volume

RUN apt-get update && \
    apt-get -y install cmake libc++-dev libc++abi-dev

RUN rustup default nightly-2020-08-13-x86_64-unknown-linux-gnu && \
rustup component add rustfmt --toolchain nightly-2020-08-13-x86_64-unknown-linux-gnu

CMD cargo build && cargo tarpaulin
